### PR TITLE
🌐 fix fr translation for starting index

### PR DESCRIPTION
**Pull request by jeremie-H**
Hello there,

It's just a little fix in french confirmation prompt.
I think there was a copy/paste, but it was weird when using in french and ask for password when it should ask to confirm for index

### CODE REVIEW

**Comment by wackerow** [comment]
Thanks @jeremie-H! This LGTM.. @lukassim I don't see this string in Crowdin (and I see some old ones in there that are no longer used)... should we upload these to Crowdin again to double check everything is correct?

**Comment by CarlBeek** [comment]
Hey @jeremie-H, you are correct that is a mistake in the transaltion, thank you. Could you rebase off of the `dev` branch (as that is the staging branch) please. That was I can get it merged ASAP. :)

@wackerow, yes we're probably overdue for annother round of crowdin cleanup.

**Comment by jeremie-H** [comment]
is it better like that ? :)

**Review by CarlBeek — APPROVED** [review]
Yes, thanks @jeremie-H!

**Pull request merged**
