### PR TITLE
[README] Add GitPOAP Badge to Display Number of Minted GitPOAPs for Contributors

### PR DESCRIPTION
**Pull request by burz**
Hey all, this PR adds a [GitPOAP Badge](https://docs.gitpoap.io/api#get-v1repoownernamebadge) to the README that displays the number of minted GitPOAPs for this repository by contributors to this repo.

You can see an example of this in [our Documentation repository](https://github.com/gitpoap/gitpoap-docs#gitpoap-docs).

This should help would-be contributors as well as existing contributors find out that they will/have received GitPOAPs for their contributions.

CC: @colfax23 @kayla-henrie

### CODE REVIEW

**Review by wackerow — APPROVED** [review]
@CarlBeek Fyi, this same feature was added to the ethereum.org repo as well for reference:
https://github.com/ethereum/ethereum-org-website/pull/7025

**Review by hwwhww — CHANGES_REQUESTED** [review]
Hi @burz, could you rebase this PR to based on the `dev` branch? Thanks!

**Review by hwwhww — APPROVED** [review]
LGTM!

**Review by Romek-cloud — COMMENTED** [review]
Romek

**Pull request merged**
